exe: main.c parser.h parser.c definitions.h definitions.c opcodes.c opcode.h label_table.h label_table.c
	gcc main.c parser.h parser.c definitions.h definitions.c opcodes.c opcode.h label_table.h label_table.c -o exe
